# Generated by Django 2.1.7 on 2019-08-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id_depo', models.AutoField(primary_key=True, serialize=False)),
                ('departamento_nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('departamento_limite_limpieza', models.FloatField(default=0, verbose_name='Limite de gastos limpieza')),
                ('departamento_limite_papeleria', models.FloatField(default=0, verbose_name='Limite de gastos papeleria')),
                ('departamento_limite_venta', models.FloatField(default=0, verbose_name='Limite de gastos consumo venta')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('empresa_tipo', models.CharField(max_length=20, verbose_name='Tipo de empresa')),
                ('empresa_abrebiacion', models.CharField(max_length=10, verbose_name='Abrebiacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenece_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertenece_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento')),
                ('pertenece_id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Es parte de',
                'verbose_name_plural': 'Es parte de',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal_nombre', models.CharField(max_length=150, verbose_name='Nombre de Sucursal')),
                ('sucursal_direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('sucursal_tipo_sucursal', models.IntegerField(choices=[(1, 'Premium'), (2, 'Estandar'), (3, 'Basico')], default=2, verbose_name='Tipo sucursal')),
                ('sucursal_empresa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
                'ordering': ['sucursal_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.AutoField(primary_key=True, serialize=False)),
                ('zona_nombre', models.CharField(max_length=80, verbose_name='Nombre de zona')),
            ],
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_id_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Sucursal', verbose_name='Sucursal'),
        ),
    ]
