# Generated by Django 2.1.7 on 2019-08-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='departamento_limite_limpieza',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='departamento_limite_papeleria',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='departamento_limite_venta',
        ),
    ]
