# Generated by Django 2.1.7 on 2019-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli', models.AutoField(primary_key=True, serialize=False)),
                ('cli_clave', models.CharField(max_length=15, unique=True, verbose_name='Clave Cliente')),
                ('cli_calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('cli_colonia', models.CharField(max_length=250, verbose_name='Colonia')),
                ('cli_cp', models.CharField(max_length=5, verbose_name='Codigo Postal')),
                ('cli_estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cli_telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('cli_rfc', models.CharField(max_length=15, verbose_name='R.F.C')),
                ('cli_email', models.CharField(max_length=80, verbose_name='Email')),
                ('cli_status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], verbose_name='Status')),
            ],
        ),
    ]
