# Generated by Django 2.1.5 on 2019-02-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertenece_empresa',
            name='pertenece_empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento'),
        ),
    ]
