# Generated by Django 2.1.7 on 2019-08-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190823_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['departamento_nombre']},
        ),
    ]
