# Generated by Django 2.1.5 on 2019-02-07 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190207_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertenece_empresa',
            name='pertenece_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento'),
        ),
        migrations.AlterField(
            model_name='pertenece_empresa',
            name='pertenece_id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
