# Generated by Django 2.1.7 on 2019-02-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20190207_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pertenece_empresa',
            options={'verbose_name': 'Es parte de', 'verbose_name_plural': 'Es parte de'},
        ),
    ]
