# Generated by Django 2.1.7 on 2019-10-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0003_cliente_cli_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cli_vndedor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado'),
        ),
    ]
