# Generated by Django 2.1.7 on 2019-10-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_cliente_cli_vndedor_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empresa_logo',
            field=models.ImageField(null=True, upload_to='empresa/logo/', verbose_name='Logo empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_telefono',
            field=models.CharField(max_length=300, verbose_name='Telefono'),
        ),
    ]
