# Generated by Django 2.1.7 on 2019-10-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_cliente_cli_vndedor_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_telefono',
            field=models.CharField(max_length=300, verbose_name='Telefono'),
        ),
    ]
