# Generated by Django 2.1.7 on 2019-10-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20191017_1205'),
        ('empresa', '0005_auto_20191018_0636'),
    ]

    operations = [
    ]
