# Generated by Django 2.1.7 on 2019-10-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_merge_20191018_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': '5. Clientes'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['departamento_nombre'], 'verbose_name_plural': '4. Departamento'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': '1. Empresa'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['sucursal_nombre'], 'verbose_name_plural': '3. Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'verbose_name_plural': '2. Zonas'},
        ),
    ]
