# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='abrebiacion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
