# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0002_empresa_abrebiacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='empresa',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Empresa'),
        ),
    ]
