# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0003_auto_20190116_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre_suc'], 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_suc',
            field=models.CharField(max_length=150, verbose_name='Nombre de Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='zona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Zona', verbose_name='id de Zona'),
        ),
    ]
