# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0004_auto_20190116_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='zona_id',
            new_name='id_zona',
        ),
    ]
