# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0005_auto_20190116_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='id_zona',
        ),
    ]
