# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0006_remove_sucursal_id_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='id_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Zona'),
        ),
    ]
