# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0007_sucursal_id_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Sucursal')),
            ],
        ),
    ]
