# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0008_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='limite_gasto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
