# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0009_departamento_limite_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['sucursal_nombre'], 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='id_depo',
            new_name='departamento_id_depo',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='id_sucursal',
            new_name='departamento_id_sucursal',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='limite_gasto',
            new_name='departamento_limite_gasto',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='nombre_suc',
            new_name='sucursal_nombre',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='abrebiacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='id_zona',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='tipo_sucursal',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='nombre_zona',
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_abrebiacion',
            field=models.CharField(max_length=10, null=True, verbose_name='Abrebiacion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_tipo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de empresa'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_id_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_tipo_sucursal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo sucursal'),
        ),
        migrations.AddField(
            model_name='zona',
            name='zona_nombre',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre de zona'),
        ),
    ]
