# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0011_auto_20190118_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamento_id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento_limite_gasto',
            field=models.FloatField(blank=True, null=True, verbose_name='Limite de gastos'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento_nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
    ]
