# Generated by Django 2.1.7 on 2019-09-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0004_auto_20190921_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('ods', models.BigAutoField(primary_key=True, serialize=False)),
                ('ods_adicion', models.DateField(auto_now_add=True)),
                ('ods_tipo_serv', models.IntegerField(choices=[(1, 'Preventivo'), (2, 'Correctivo')], verbose_name='Tipo de servicio')),
                ('ods_falla_rep', models.CharField(max_length=600, verbose_name='Falla reportada por el usuario')),
                ('ods_diagnostico', models.CharField(max_length=600, verbose_name='Diagnostico Tecnico')),
                ('ods_observacion', models.CharField(max_length=600, verbose_name='Observaciones')),
                ('ods_doc', models.FileField(upload_to='ods/documento/validacion', verbose_name='PDF firmado')),
                ('ods_status', models.IntegerField(choices=[(1, 'Abierto'), (2, 'Asignado'), (3, 'En Proceso'), (4, 'Finalizado')], verbose_name='Estatus')),
                ('ods_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.Asignacion', verbose_name='Seleccione asignación')),
                ('ods_delegar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='Empresa ala que desea delegar orden de servicio')),
                ('ods_user_creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('ods_user_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserTecnicoOds', to=settings.AUTH_USER_MODEL, verbose_name='Usuario tecnico atendiendo ods')),
            ],
        ),
    ]
