# Generated by Django 2.1.7 on 2019-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ods', '0002_auto_20190924_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenservicio',
            options={'permissions': [('usuario_soporte_tecnico_ods', 'Usuario soporte tecnico')]},
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='ods_status',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'Asignado y en Proceso'), (3, 'Soporte terminado'), (4, 'Cerrado')], verbose_name='Estatus'),
        ),
    ]
