# Generated by Django 2.1.7 on 2019-10-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tipo_pedido_tp_empresa'),
        ('ods', '0004_auto_20191001_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('ref', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref_precio', models.FloatField(verbose_name='Precio refaccion')),
                ('ref_cantidad', models.FloatField(verbose_name='Precio refaccion')),
                ('ref_obsrv', models.CharField(max_length=200, verbose_name='Observacion')),
                ('ref_produc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Producto', verbose_name='Elija un producto')),
            ],
        ),
    ]
