# Generated by Django 2.1.7 on 2019-10-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ods', '0005_refaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='ref_ods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ods.OrdenServicio', verbose_name='Elija un ODS'),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='ref_cantidad',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
