# Generated by Django 2.1.7 on 2019-10-03 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ods', '0006_auto_20191002_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='ref_cantidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
