# Generated by Django 2.1.7 on 2019-10-03 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('ods', '0007_auto_20191003_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='ref_add_fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refaccion',
            name='ref_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento', verbose_name='Departamento'),
        ),
    ]
