# Generated by Django 2.1.7 on 2019-08-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Client_numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de cliente')),
                ('Client_Nombre', models.CharField(max_length=80, verbose_name='Nombre de cliente')),
                ('Client_Estatus', models.BooleanField(verbose_name='Activo')),
                ('Client_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conformidad',
            fields=[
                ('conformidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('conformidad_descripcion', models.CharField(max_length=150, verbose_name='Descripción de conformidad')),
                ('conformidad_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fud',
            fields=[
                ('Folio', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroVenta', models.IntegerField(default='', verbose_name='Número de venta')),
                ('Factura', models.CharField(blank=True, default='TCA0', max_length=150, null=True, verbose_name='Factura')),
                ('FechaFactura', models.DateField(default='2017-01-01')),
                ('factura_total', models.FloatField(default='0.00', verbose_name='Valor de la factura')),
                ('devolucion', models.IntegerField(blank=True, choices=[(1, 'Total'), (2, 'Parcial'), (3, 'N/A')], default=1, null=True, verbose_name='Estado')),
                ('responsable', models.CharField(max_length=80)),
                ('observaciones', models.CharField(max_length=1500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('EstadoFud', models.IntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Autorizado'), (3, 'En transito'), (4, 'Entregado'), (5, 'Finalizado')], default=1, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('motivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_descripcion', models.CharField(max_length=150, verbose_name='Descripción de motivo')),
                ('motivo_fechaAlta', models.DateTimeField(auto_now_add=True)),
                ('motivo_idconformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuds.Conformidad', verbose_name='Id conformidad')),
            ],
        ),
        migrations.CreateModel(
            name='PartidasFud',
            fields=[
                ('Partida_id', models.AutoField(primary_key=True, serialize=False)),
                ('Partida_Precio', models.FloatField(default=0, verbose_name='Precio de la partida')),
                ('Partida_Cantidad', models.IntegerField(default=1, verbose_name='cantidad de partidas')),
                ('Partida_FechaAlta', models.DateTimeField(auto_now_add=True)),
                ('Partida_fud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuds.Fud', verbose_name='Fud a seleccionar')),
                ('Partida_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Producto', verbose_name='Partida de fud')),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.AutoField(primary_key=True, serialize=False)),
                ('tramite_descripcion', models.CharField(max_length=150, verbose_name='Descripción de trámite')),
                ('tramite_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('Vend_id', models.AutoField(primary_key=True, serialize=False)),
                ('Vend_nombre', models.CharField(max_length=80, verbose_name='Nombre del vendedor')),
                ('Vend_Estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado de vendedor')),
                ('Vend_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('Zona_id', models.AutoField(primary_key=True, serialize=False)),
                ('Zona_nombre', models.CharField(max_length=80, verbose_name='Nombre de la Zona')),
                ('Zona_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vendedores',
            name='Vend_Zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Zona', verbose_name='Zona a la que pertenece el vendedor'),
        ),
        migrations.AddField(
            model_name='fud',
            name='Motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Motivo'),
        ),
        migrations.AddField(
            model_name='fud',
            name='NumeroCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Clientes', verbose_name='Número de cliente'),
        ),
        migrations.AddField(
            model_name='fud',
            name='VendedorCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Vendedores', verbose_name='Vendedor asignado al cliente'),
        ),
        migrations.AddField(
            model_name='fud',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fud',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Tramite'),
        ),
    ]
