# Generated by Django 2.1.7 on 2019-03-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conformidad',
            fields=[
                ('conformidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('conformidad_descripcion', models.CharField(max_length=150, verbose_name='Descripción de conformidad')),
                ('conformidad_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaFactura', models.DateField(default='2017-01-01')),
                ('factura_folio', models.CharField(max_length=100)),
                ('factura_total', models.FloatField(verbose_name='Valor de la factura')),
                ('factura_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fud',
            fields=[
                ('Folio', models.AutoField(primary_key=True, serialize=False)),
                ('FechaFactura', models.DateField(blank=True, null=True)),
                ('NumeroCliente', models.IntegerField(default=1, verbose_name='Número de cliente')),
                ('NombreCliente', models.CharField(default='no identificado', max_length=80, verbose_name='Nombre de cliente')),
                ('ZonaCliente', models.CharField(default='no identificado', max_length=80, verbose_name='Zona que pertence el cliente')),
                ('VendedorCliente', models.CharField(default='no identificado', max_length=80, verbose_name='Vendedor asignado al cliente')),
                ('devolucion', models.IntegerField(blank=True, choices=[(1, 'Total'), (2, 'Parcial'), (3, 'N/A')], default=1, null=True, verbose_name='Estado')),
                ('responsable', models.CharField(max_length=80)),
                ('observaciones', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.CharField(max_length=150)),
                ('Factura', models.ManyToManyField(to='fuds.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('motivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_descripcion', models.CharField(max_length=150, verbose_name='Descripción de motivo')),
                ('motivo_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.AutoField(primary_key=True, serialize=False)),
                ('tramite_descripcion', models.CharField(max_length=150, verbose_name='Descripción de trámite')),
                ('tramite_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendedor_nombre', models.CharField(max_length=150, verbose_name='Nombre de vendedor')),
                ('vendedor_estatus', models.IntegerField(default=1, verbose_name='Estado de vendedor')),
                ('vendedor_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fud',
            name='Motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Motivo'),
        ),
        migrations.AddField(
            model_name='fud',
            name='conformidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Conformidad'),
        ),
        migrations.AddField(
            model_name='fud',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Tramite'),
        ),
    ]
