# Generated by Django 2.2 on 2019-04-09 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conformidad',
            fields=[
                ('conformidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('conformidad_descripcion', models.CharField(max_length=150, verbose_name='Descripción de conformidad')),
                ('conformidad_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.AutoField(primary_key=True, serialize=False)),
                ('tramite_descripcion', models.CharField(max_length=150, verbose_name='Descripción de trámite')),
                ('tramite_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendedor_nombre', models.CharField(max_length=150, verbose_name='Nombre de vendedor')),
                ('vendedor_estatus', models.IntegerField(default=1, verbose_name='Estado de vendedor')),
                ('vendedor_fechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('motivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_descripcion', models.CharField(max_length=150, verbose_name='Descripción de motivo')),
                ('motivo_fechaAlta', models.DateTimeField(auto_now_add=True)),
                ('motivo_idconformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuds.Conformidad', verbose_name='Id conformidad')),
            ],
        ),
        migrations.CreateModel(
            name='Fud',
            fields=[
                ('Folio', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroCliente', models.IntegerField(default=1, verbose_name='Número de cliente')),
                ('NombreCliente', models.CharField(default='no identificado', max_length=80, verbose_name='Nombre de cliente')),
                ('ZonaCliente', models.CharField(default='no identificado', max_length=80, verbose_name='Zona que pertence el cliente')),
                ('VendedorCliente', models.CharField(default='no identificado', max_length=80, verbose_name='Vendedor asignado al cliente')),
                ('Factura', models.CharField(blank=True, max_length=150, null=True, verbose_name='Factura')),
                ('FechaFactura', models.DateField(default='2017-01-01')),
                ('factura_total', models.FloatField(default='0.00', verbose_name='Valor de la factura')),
                ('devolucion', models.IntegerField(blank=True, choices=[(1, 'Total'), (2, 'Parcial'), (3, 'N/A')], default=1, null=True, verbose_name='Estado')),
                ('responsable', models.CharField(max_length=80)),
                ('observaciones', models.CharField(max_length=1500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Motivo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Tramite')),
            ],
        ),
    ]
