# Generated by Django 2.1.7 on 2019-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('fuds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidasFud',
            fields=[
                ('Partida_id', models.AutoField(primary_key=True, serialize=False)),
                ('Partida_FechaAlta', models.DateTimeField(auto_now_add=True)),
                ('Partida_nombre', models.ManyToManyField(blank=True, null=True, to='pedidos.Producto', verbose_name='Partida de fud')),
            ],
        ),
    ]
