# Generated by Django 2.1.7 on 2019-11-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='NumeroCliente',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='fuds.Clientes', verbose_name='Número de cliente'),
        ),
    ]
