# Generated by Django 2.1.7 on 2019-04-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('Vend_id', models.AutoField(primary_key=True, serialize=False)),
                ('Vend_nombre', models.CharField(max_length=80, verbose_name='Nombre del vendedor')),
                ('Vend_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('Zona_id', models.AutoField(primary_key=True, serialize=False)),
                ('Zona_nombre', models.CharField(max_length=80, verbose_name='Nombre de la Zona')),
                ('Zona_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vendedores',
            name='Vend_Zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Zona', verbose_name='Zona a la que pertenece el vendedor'),
        ),
    ]
