# Generated by Django 2.1.7 on 2019-03-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='FechaFactura',
            field=models.DateField(default='2019-03-01'),
        ),
    ]
