# Generated by Django 2.1.7 on 2019-03-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0002_auto_20190325_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='observaciones',
            field=models.CharField(max_length=1500),
        ),
    ]
