# Generated by Django 2.1.7 on 2019-04-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0002_partidasfud'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidasfud',
            name='Partida_Cantidad',
            field=models.IntegerField(default=1, verbose_name='cantidad de partidas'),
        ),
        migrations.AddField(
            model_name='partidasfud',
            name='Partida_Precio',
            field=models.FloatField(default=0, verbose_name='Precio de la partida'),
        ),
    ]
