# Generated by Django 2.1.7 on 2019-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0002_auto_20190301_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factura_folio',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
