# Generated by Django 2.1.7 on 2019-04-22 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0002_auto_20190422_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fud',
            name='ZonaCliente',
        ),
        migrations.AlterField(
            model_name='fud',
            name='VendedorCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Vendedores', verbose_name='Vendedor asignado al cliente'),
        ),
    ]
