# Generated by Django 2.1.7 on 2019-11-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0002_auto_20191120_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='NumeroCliente',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Clientes', verbose_name='Número de cliente'),
        ),
    ]
