# Generated by Django 2.1.7 on 2020-01-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0003_auto_20191120_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidasfud',
            name='Partida_Descuento',
            field=models.FloatField(default=0, verbose_name='Descuento de la partida'),
        ),
    ]
