# Generated by Django 2.1.7 on 2019-04-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0003_auto_20190425_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fud',
            name='Partida_nombre',
            field=models.ManyToManyField(blank=True, null=True, to='fuds.PartidasFud', verbose_name='Partida de fud'),
        ),
    ]
