# Generated by Django 2.1.7 on 2019-04-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0003_auto_20190422_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.AddField(
            model_name='vendedores',
            name='Vend_Estatus',
            field=models.IntegerField(default=1, verbose_name='Estado de vendedor'),
        ),
    ]
