# Generated by Django 2.1.7 on 2019-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0004_fud_partida_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidasfud',
            name='Partida_nombre',
        ),
        migrations.AlterField(
            model_name='fud',
            name='Partida_nombre',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.Producto', verbose_name='Partida de fud'),
        ),
        migrations.DeleteModel(
            name='PartidasFud',
        ),
    ]
