# Generated by Django 2.1.7 on 2019-04-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0004_auto_20190422_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='Vend_Estatus',
            field=models.IntegerField(choices=[(1, 'Persona Fisica'), (2, 'Persona Moral')], default=1, verbose_name='Estado de vendedor'),
        ),
    ]
