# Generated by Django 2.1.7 on 2020-01-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0004_partidasfud_partida_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidasfud',
            name='Partida_Descuento',
        ),
        migrations.AddField(
            model_name='fud',
            name='Descuento',
            field=models.FloatField(default=0, verbose_name='Descuento del pedido'),
        ),
    ]
