# Generated by Django 2.1.7 on 2020-01-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0005_auto_20200103_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='Descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento del pedido'),
        ),
    ]
