# Generated by Django 2.1.7 on 2019-04-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('fuds', '0005_auto_20190426_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidasFud',
            fields=[
                ('Partida_id', models.AutoField(primary_key=True, serialize=False)),
                ('Partida_Precio', models.FloatField(default=0, verbose_name='Precio de la partida')),
                ('Partida_Cantidad', models.IntegerField(default=1, verbose_name='cantidad de partidas')),
                ('Partida_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fud',
            name='Partida_nombre',
        ),
        migrations.AddField(
            model_name='partidasfud',
            name='Partida_fud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuds.Fud', verbose_name='Fud a seleccionar'),
        ),
        migrations.AddField(
            model_name='partidasfud',
            name='Partida_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Producto', verbose_name='Partida de fud'),
        ),
    ]
