# Generated by Django 2.1.7 on 2019-05-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0006_auto_20190426_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='fud',
            name='EstadoFud',
            field=models.IntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Autorizados'), (3, 'En transito'), (4, 'Entregados'), (5, 'Finalizados')], default=1, null=True, verbose_name='Estado'),
        ),
    ]
