# Generated by Django 2.2.1 on 2019-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0007_fud_estadofud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='EstadoFud',
            field=models.IntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Autorizado'), (3, 'En transito'), (4, 'Entregado'), (5, 'Finalizado')], default=1, null=True, verbose_name='Estado'),
        ),
    ]
