# Generated by Django 2.1.7 on 2019-07-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0008_auto_20190523_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fud',
            name='NumeroVenta',
            field=models.IntegerField(default=0, verbose_name='Número de venta'),
        ),
    ]
