# Generated by Django 2.1.7 on 2019-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0009_fud_numeroventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='NumeroVenta',
            field=models.IntegerField(default=1, verbose_name='Número de venta'),
        ),
    ]
