# Generated by Django 2.1.7 on 2019-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0011_auto_20190719_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='Factura',
            field=models.CharField(blank=True, default='TCA0', max_length=150, null=True, verbose_name='Factura'),
        ),
    ]
