# Generated by Django 2.1.7 on 2019-07-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0012_auto_20190719_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Client_numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nombre del cliente')),
                ('Client_Nombre', models.CharField(max_length=80, verbose_name='Nombre de cliente')),
                ('Client_Estatus', models.BooleanField(verbose_name='Activo')),
                ('Client_FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fud',
            name='NombreCliente',
        ),
        migrations.AlterField(
            model_name='fud',
            name='NumeroCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuds.Clientes', verbose_name='Número de cliente'),
        ),
    ]
