# Generated by Django 2.1.7 on 2019-07-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0014_auto_20190719_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='NumeroVenta',
            field=models.IntegerField(default=0, verbose_name='Número de venta'),
        ),
    ]
