# Generated by Django 2.1.7 on 2019-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuds', '0015_auto_20190719_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fud',
            name='NumeroVenta',
            field=models.IntegerField(verbose_name='Número de venta'),
        ),
    ]
