# Generated by Django 2.2 on 2019-04-25 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=40, verbose_name='Nombre de area')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nombre', models.CharField(max_length=80, verbose_name='Nombre de Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('producto_descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('producto_imagen', models.ImageField(upload_to='img_productos/', verbose_name='Imagen')),
                ('producto_precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio')),
                ('tipo_producto', models.IntegerField(blank=True, choices=[(1, 'Uso Interno'), (2, 'Activo Fijo')], null=True)),
                ('producto_es_kit', models.BooleanField(default=False, verbose_name='Pertenecera a un Kit')),
                ('producto_kit', models.BooleanField(default=False, verbose_name='Kit')),
                ('producto_categoria', models.IntegerField(choices=[(1, 'Limpieza'), (2, 'Papeleria'), (3, 'Consumo Venta')], default=1, verbose_name='Categoria de producto')),
                ('producto_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Area', verbose_name='Area')),
                ('producto_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Marca', verbose_name='Marca')),
                ('producto_productos', models.ManyToManyField(to='pedidos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('pedido_status', models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1, verbose_name='Status')),
                ('pedido_tipo', models.IntegerField(choices=[(1, 'Limpieza'), (2, 'Papeleria'), (3, 'Consumo Venta')], default=1, verbose_name='Categoria de producto')),
                ('pedido_autorizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autorizador', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por')),
                ('pedido_id_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento', verbose_name='Departamento')),
                ('pedido_rechazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cancelo', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado Por')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detallepedido_cantidad', models.FloatField(blank=True, null=True, verbose_name='Cantidad')),
                ('detallepedido_precio', models.FloatField(default=0)),
                ('detallepedido_status', models.BooleanField(default=False)),
                ('detallepedido_categoria', models.IntegerField(choices=[(1, 'Limpieza'), (2, 'Papeleria'), (3, 'Consumo Venta')], default=1, verbose_name='Pedido')),
                ('detallepedido_creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('detallepedido_pedido_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido', verbose_name='Numero de pedido')),
                ('detallepedido_producto_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Detalle de pedidos',
                'ordering': ['detallepedido_pedido_id'],
            },
        ),
    ]
