# Generated by Django 2.1.5 on 2019-02-02 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=40, verbose_name='Nombre de area')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detallepedido_cantidad', models.FloatField(blank=True, null=True, verbose_name='Cantidad')),
                ('detallepedido_precio', models.FloatField(default=0)),
                ('detallepedido_creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalle de pedidos',
                'ordering': ['detallepedido_pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nombre', models.CharField(max_length=80, verbose_name='Nombre de Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('pedido_status', models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1, verbose_name='Status')),
                ('pedido_id_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('producto_descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='img_productos/', verbose_name='Imagen')),
                ('producto_precio', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('tipo_producto', models.IntegerField(blank=True, choices=[(1, 'Uso Interno'), (2, 'Activo Fijo')], null=True)),
                ('producto_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Area', verbose_name='Area')),
                ('producto_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Marca', verbose_name='Marca')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_pedido_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido', verbose_name='Numero de pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Producto', verbose_name='Producto'),
        ),
    ]
