# Generated by Django 2.1.7 on 2019-09-07 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=40, verbose_name='Nombre de area')),
            ],
        ),
        migrations.CreateModel(
            name='Asignar_gasto_sucursal',
            fields=[
                ('ags', models.AutoField(primary_key=True, serialize=False)),
                ('ags_maximo_gasto', models.FloatField(verbose_name='Maximo de gasto')),
                ('ags_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_pedido',
            fields=[
                ('conf_ID', models.AutoField(primary_key=True, serialize=False)),
                ('conf_fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('conf_fecha_fin', models.DateField(verbose_name='Fecha final')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detallepedido_cantidad', models.FloatField(blank=True, null=True, verbose_name='Cantidad')),
                ('detallepedido_precio', models.FloatField(default=0)),
                ('detallepedido_tipo_pedido', models.IntegerField(default=0)),
                ('detallepedido_status', models.BooleanField(default=False)),
                ('detallepedido_creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalle de pedidos',
                'ordering': ['detallepedido_pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nombre', models.CharField(max_length=80, verbose_name='Nombre de Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_fecha_pedido', models.DateField(auto_now_add=True)),
                ('pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('pedido_status', models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Cancelado'), (4, 'Venta'), (5, 'Facturado'), (6, 'Finalizado'), (7, 'Descargado')], default=1, verbose_name='Status')),
                ('pedido_n_factura', models.CharField(blank=True, max_length=14, null=True, verbose_name='Folio Factura')),
                ('pedido_n_salida', models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero Salida')),
                ('pedido_n_cresscedo', models.CharField(blank=True, max_length=14, null=True, verbose_name='Venta Cresscendo')),
                ('pedido_Descargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Descargado', to=settings.AUTH_USER_MODEL, verbose_name='Descargado Por')),
                ('pedido_Facturado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Facturado', to=settings.AUTH_USER_MODEL, verbose_name='Facturado Por')),
                ('pedido_Finalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Finalizado', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado Por')),
                ('pedido_Venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to=settings.AUTH_USER_MODEL, verbose_name='Venta Por')),
                ('pedido_autorizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autorizador', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por')),
                ('pedido_id_depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento', verbose_name='Departamento')),
                ('pedido_rechazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cancelo', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado Por')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('producto_descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('producto_imagen', models.ImageField(upload_to='img_productos/', verbose_name='Imagen')),
                ('producto_precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio')),
                ('tipo_producto', models.IntegerField(blank=True, choices=[(1, 'Uso Interno'), (2, 'Activo Fijo')], null=True)),
                ('producto_es_kit', models.BooleanField(default=False, verbose_name='¿Pertenecerá a un Kit?')),
                ('producto_kit', models.BooleanField(default=False, verbose_name='Kit')),
                ('producto_visible', models.BooleanField(default=True, verbose_name='¿Producto visible?')),
                ('producto_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Area', verbose_name='Area')),
                ('producto_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Marca', verbose_name='Marca')),
                ('producto_productos', models.ManyToManyField(to='pedidos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pedido',
            fields=[
                ('tp', models.AutoField(primary_key=True, serialize=False)),
                ('tp_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('tp_descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('tp_max_ped_mes', models.IntegerField(default=1, verbose_name='Cantidad de pedidos por mes')),
                ('tp_imagen', models.ImageField(upload_to='imgCategoria/', verbose_name='Imagen')),
                ('tp_productos', models.ManyToManyField(to='pedidos.Producto', verbose_name='Productos')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_tipoPedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Tipo_Pedido', verbose_name='Tipo de pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_pedido_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido', verbose_name='Numero de pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='asignar_gasto_sucursal',
            name='ags_tipo_ped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Tipo_Pedido', verbose_name='Tipo pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='asignar_gasto_sucursal',
            unique_together={('ags_tipo_ped', 'ags_sucursal')},
        ),
    ]
