# Generated by Django 2.2.1 on 2019-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_pedido',
            fields=[
                ('conf_ID', models.AutoField(primary_key=True, serialize=False)),
                ('conf_fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('conf_fecha_fin', models.DateField(verbose_name='Fecha final')),
            ],
        ),
    ]
