# Generated by Django 2.1.7 on 2019-08-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pedido',
            fields=[
                ('tp', models.AutoField(primary_key=True, serialize=False)),
                ('tp_nombre', models.CharField(max_length=30)),
                ('tp_descripcion', models.CharField(max_length=50)),
                ('tp_imagen', models.ImageField(max_length=10, upload_to='imgCategoria/')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='detallepedido_categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_categoria',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_n_factura',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero Salida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Descargado'), (4, 'Venta'), (5, 'Facturado'), (6, 'Finalizado')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_es_kit',
            field=models.BooleanField(default=False, verbose_name='¿Pertenecerá a un Kit?'),
        ),
        migrations.AddField(
            model_name='tipo_pedido',
            name='tp_productos',
            field=models.ManyToManyField(to='pedidos.Producto', verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_tipoPedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Tipo_Pedido', verbose_name='Tipo de pedido'),
        ),
    ]
