# Generated by Django 2.1.7 on 2019-02-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_status',
            field=models.BooleanField(default=False),
        ),
    ]
