# Generated by Django 2.1.7 on 2019-08-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20190820_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_pedido',
            name='tp_descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipo_pedido',
            name='tp_imagen',
            field=models.ImageField(upload_to='imgCategoria/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tipo_pedido',
            name='tp_nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
