# Generated by Django 2.1.7 on 2019-10-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20191017_1205'),
        ('pedidos', '0002_tipo_pedido_tp_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_catalogo', models.CharField(max_length=30, verbose_name='Nombre')),
                ('tp_descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('tp_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='Empresa')),
                ('tp_productos', models.ManyToManyField(to='pedidos.Producto', verbose_name='Productos')),
            ],
        ),
    ]
