# Generated by Django 2.2.1 on 2019-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_configuracion_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
    ]
