# Generated by Django 2.1.7 on 2019-02-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detalle_pedido_detallepedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_productos',
            field=models.ManyToManyField(to='pedidos.Producto'),
        ),
    ]
