# Generated by Django 2.1.7 on 2019-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_producto_producto_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_es_kit',
            field=models.BooleanField(default=False, verbose_name='Es Kit'),
        ),
    ]
