# Generated by Django 2.2.1 on 2019-06-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20190523_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_n_cresscedo',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Folio Factura'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_n_factura',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Folio Factura'),
        ),
    ]
