# Generated by Django 2.1.7 on 2019-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_catalogo_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_productos',
            name='tp_imagen',
            field=models.ImageField(null=True, upload_to='catalogo_prod/licitacion/', verbose_name='Imagen empresa a licitar'),
        ),
        migrations.AddField(
            model_name='catalogo_productos',
            name='tp_no_licitacion',
            field=models.CharField(max_length=100, null=True, verbose_name='N° de Licitacion'),
        ),
        migrations.AlterField(
            model_name='catalogo_productos',
            name='tp_catalogo',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='catalogo_productos',
            name='tp_descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
