# Generated by Django 2.1.7 on 2019-08-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('pedidos', '0003_auto_20190821_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignar_gasto_sucursal',
            fields=[
                ('ags', models.AutoField(primary_key=True, serialize=False)),
                ('ags_maximo_gasto', models.FloatField(verbose_name='Maximo de gasto')),
                ('ags_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento', verbose_name='Sucursales')),
                ('ags_tipo_ped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Tipo_Pedido', verbose_name='Tipo pedido')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asignar_gasto_sucursal',
            unique_together={('ags_tipo_ped', 'ags_sucursal')},
        ),
    ]
