# Generated by Django 2.1.7 on 2019-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20191022_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_productos',
            name='tp_fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
