# Generated by Django 2.1.7 on 2019-02-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_producto_producto_es_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_kit',
            field=models.BooleanField(default=False, verbose_name='Kit'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_es_kit',
            field=models.BooleanField(default=False, verbose_name='Pertenecera a un Kit'),
        ),
    ]
