# Generated by Django 2.2.1 on 2019-07-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20190605_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_visible',
            field=models.BooleanField(default=True, verbose_name='¿Producto visible?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_n_cresscedo',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Venta Cresscendo'),
        ),
    ]
