# Generated by Django 2.1.7 on 2019-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20190220_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(upload_to='img_productos/', verbose_name='Imagen'),
        ),
    ]
