# Generated by Django 2.1.7 on 2019-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_catalogo_productos_tp_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_productos',
            name='tp_fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
