# Generated by Django 2.1.7 on 2019-08-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20190823_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_pedido',
            name='tp_max_ped_mes',
            field=models.IntegerField(default=1, verbose_name='Cantidad de pedidos por mes'),
        ),
    ]
