# Generated by Django 2.1.7 on 2019-07-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20190719_1614'),
        ('pedidos', '0005_auto_20190719_1557'),
    ]

    operations = [
    ]
