# Generated by Django 2.1.7 on 2019-08-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_tipo_pedido_tp_max_ped_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_tipo_pedido',
            field=models.IntegerField(default=0),
        ),
    ]
