# Generated by Django 2.1.7 on 2019-10-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20191023_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_productos',
            name='tp_fecha',
            field=models.CharField(max_length=50, verbose_name='Fecha'),
        ),
    ]
