# Generated by Django 2.1.7 on 2019-08-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0007_detalle_pedido_detallepedido_tipo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_Descargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Descargado', to=settings.AUTH_USER_MODEL, verbose_name='Descargado Por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_Facturado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Facturado', to=settings.AUTH_USER_MODEL, verbose_name='Facturado Por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_Finalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Finalizado', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado Por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_Venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to=settings.AUTH_USER_MODEL, verbose_name='Venta Por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Cancelado'), (4, 'Venta'), (5, 'Facturado'), (6, 'Finalizado'), (7, 'Descargado')], default=1, verbose_name='Status'),
        ),
    ]
