# Generated by Django 2.2 on 2019-04-11 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0007_auto_20190409_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_autorizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autorizador', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_rechazado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cancelo', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado Por'),
        ),
    ]
