# Generated by Django 2.1.7 on 2019-10-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20191023_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_productos',
            name='tp_fecha',
        ),
    ]
