# Generated by Django 2.1.7 on 2019-08-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20190826_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_n_salida',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero Salida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_n_factura',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Folio Factura'),
        ),
    ]
