# Generated by Django 2.1.7 on 2019-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_catalogo_productos_tp_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_productos',
            name='tp_orientacion_t',
            field=models.IntegerField(choices=[(1, 'Derecha'), (2, 'Izquierda')], default=1),
        ),
    ]
