# Generated by Django 2.1.7 on 2019-12-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0010_auto_20191120_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inv', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_cant_resguardo', models.IntegerField(verbose_name='Cantidad encontrada en resguardo')),
                ('inv_cant_piking', models.IntegerField(verbose_name='Cantidad encontrada en piking')),
                ('inv_cant_otros', models.IntegerField(verbose_name='Cantidad encontrada en otras ubicaciones')),
                ('inv_cant_merma', models.IntegerField(verbose_name='Merma')),
                ('inv_fecha_add', models.DateTimeField(auto_now_add=True)),
                ('inv_descripcion', models.CharField(help_text='Describa la ubicacion encontrada y comentarios', max_length=500, verbose_name='Descripción')),
                ('inv_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Producto', verbose_name='Codigo producto')),
                ('inv_sup_autorizo_merma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoriza_merma', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor autorizador merma')),
                ('inv_user_catura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario capturador')),
            ],
        ),
    ]
