# Generated by Django 2.1.7 on 2019-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_merma',
            field=models.IntegerField(null=True, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_otros',
            field=models.IntegerField(null=True, verbose_name='Cantidad encontrada en otras ubicaciones'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_piking',
            field=models.IntegerField(null=True, verbose_name='Cantidad encontrada en piking'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_resguardo',
            field=models.IntegerField(null=True, verbose_name='Cantidad encontrada en resguardo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_descripcion',
            field=models.CharField(blank=True, help_text='Describa la ubicacion encontrada y comentarios', max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
