# Generated by Django 2.1.7 on 2019-12-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_auto_20191218_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'permissions': [('puede_visualizar_avance_conteo_inventario', 'Puede Ver avance del conteo de inventario')]},
        ),
    ]
