# Generated by Django 2.1.7 on 2019-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_auto_20191218_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-inv_fecha_add'], 'permissions': [('puede_visualizar_avance_conteo_inventario', 'Puede Ver avance del conteo de inventario')]},
        ),
        migrations.AddField(
            model_name='producto',
            name='prducto_codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prducto_localizacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localizacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prducto_resguardo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localizacion en resguardo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prducto_unidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad'),
        ),
    ]
