# Generated by Django 2.1.7 on 2019-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_auto_20191218_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='inv_validacion',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
