# Generated by Django 2.1.7 on 2019-12-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_inventario_inv_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_merma',
            field=models.IntegerField(default=0, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_otros',
            field=models.IntegerField(default=0, verbose_name='Cantidad encontrada en otras ubicaciones'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_piking',
            field=models.IntegerField(default=0, verbose_name='Cantidad encontrada en piking'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_cant_resguardo',
            field=models.IntegerField(default=0, verbose_name='Cantidad encontrada en resguardo'),
        ),
    ]
