# Generated by Django 2.1.7 on 2019-12-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_auto_20191220_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-inv_fecha_add'], 'permissions': [('puede_visualizar_avance_conteo_inventario', 'Puede Ver avance del conteo de inventario'), ('inventario_perm_supervisor', 'Permiso de supervisor para inventario')]},
        ),
    ]
