# Generated by Django 2.1.7 on 2019-12-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_auto_20191223_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prducto_existencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Existencia'),
        ),
    ]
