# Generated by Django 2.1.7 on 2019-12-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0018_producto_prducto_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='inv_edicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_edit', to=settings.AUTH_USER_MODEL, verbose_name='Ultimo Usuario edito'),
        ),
    ]
