# Generated by Django 2.1.7 on 2019-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_inventario_inv_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='inv_conteo',
            field=models.IntegerField(choices=[(1, 'CONTEO 1'), (2, 'CONTEO 2'), (3, 'CONTEO 3')], default=1, verbose_name='Numero de conteo'),
        ),
    ]
