# Generated by Django 2.1.7 on 2019-12-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_inventario_inv_conteo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('inv_producto', 'inv_conteo')},
        ),
    ]
