# Generated by Django 2.1.7 on 2019-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_auto_20191227_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='inv_tipo_sitio',
            field=models.IntegerField(choices=[(1, 'RESGUARDO'), (2, 'PIKING'), (3, 'OTROS'), (4, 'MERMA')], null=True, verbose_name='Ubicacion conteo'),
        ),
    ]
