# Generated by Django 2.1.7 on 2019-12-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_auto_20191227_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-inv_fecha_add'], 'permissions': [('puede_visualizar_avance_conteo_inventario', 'Puede Ver avance del conteo de inventario'), ('inventario_perm_supervisor', 'Permiso de supervisor para inventario')]},
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set(),
        ),
    ]
