# Generated by Django 2.1.7 on 2019-12-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_auto_20191227_0722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('inv_producto', 'inv_conteo', 'inv_tipo_sitio')},
        ),
    ]
