# Generated by Django 2.1.7 on 2019-08-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('activo', models.AutoField(primary_key=True, serialize=False)),
                ('activo_nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('activo_modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('activo_serie', models.CharField(max_length=30, verbose_name='Serie')),
                ('activo_codigo_barra', models.CharField(max_length=20, verbose_name='Codigo de Barra')),
                ('activo_costo', models.FloatField(verbose_name='Costo de activo')),
                ('activo_observacion', models.TextField(verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de categoria')),
                ('cat_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Area', verbose_name='Area a la que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('especificacion', models.AutoField(primary_key=True, serialize=False)),
                ('esp_item', models.CharField(max_length=120, verbose_name='Item')),
                ('esp_valor', models.CharField(max_length=100, verbose_name='Especificación')),
                ('esp_tiene_costo', models.BooleanField(default=False, verbose_name='Tiene algun costo?')),
                ('esp_costo', models.FloatField(default=0.0, verbose_name='Costo de la especificacion')),
                ('esp_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Activo', verbose_name='Activo perteneciente')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='activo_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Categoria', verbose_name='Categoria a la que pertenece'),
        ),
        migrations.AddField(
            model_name='activo',
            name='activo_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Marca', verbose_name='Marca'),
        ),
    ]
