# Generated by Django 2.1.7 on 2019-09-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20190917_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitebaja',
            name='tb_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Asignacion', verbose_name='Seleccione activo asignado'),
        ),
    ]
