# Generated by Django 2.2.1 on 2019-06-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20190603_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='activo_codigo_barra',
            field=models.CharField(max_length=20, verbose_name='Codigo de Barra'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='activo_serie',
            field=models.CharField(max_length=30, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='especificacion',
            name='esp_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Activo', verbose_name='Activo perteneciente'),
        ),
        migrations.AlterField(
            model_name='especificacion',
            name='esp_valor',
            field=models.CharField(max_length=100, verbose_name='Especificación'),
        ),
    ]
