# Generated by Django 2.1.7 on 2019-09-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_auto_20190917_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('item_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre item')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateItemGroup',
            fields=[
                ('itmg', models.AutoField(primary_key=True, serialize=False)),
                ('itmg_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de grupo')),
                ('itmg_items', models.ManyToManyField(to='activos.TemplateItem', verbose_name='Items')),
            ],
        ),
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['asig_fecha_adicion']},
        ),
        migrations.AlterField(
            model_name='tramitebaja',
            name='tb_observacion',
            field=models.CharField(max_length=600, verbose_name='Observacion o motivo por el cual se dará de baja'),
        ),
        migrations.AlterField(
            model_name='tramitebaja',
            name='tb_validado',
            field=models.BooleanField(default=0, verbose_name='Validar Baja'),
        ),
    ]
