# Generated by Django 2.1.5 on 2019-02-02 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('complemento_id', models.AutoField(primary_key=True, serialize=False)),
                ('complemento_pdf', models.FileField(upload_to='Facturas/complementos/')),
                ('complemento_monto', models.FloatField(blank=True, null=True)),
                ('complemento_metodo', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=40)),
                ('complemento_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato_id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato_documento', models.FileField(upload_to='Contratos/', verbose_name='Documento')),
                ('contrato_fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('contrato_fecha_termino', models.DateField(verbose_name='Termino')),
                ('contrato_dias_pago', models.CharField(max_length=100, verbose_name='Describa fechas de pago')),
                ('contrato_direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('contrato_monto', models.FloatField(verbose_name='Monto')),
                ('contrato_autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('contrato_status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('factura_tipo', models.IntegerField(choices=[(1, 'Persona Fisica'), (2, 'Persona Moral')])),
                ('factura_xml', models.FileField(upload_to='Facturas/xml/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('factura_pdf', models.FileField(upload_to='Facturas/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('factura_monto_total', models.FloatField(blank=True, null=True)),
                ('factura_iva_trasladado', models.FloatField(blank=True, null=True)),
                ('factura_iva_retenido', models.FloatField(blank=True, null=True)),
                ('factura_isr_retenido', models.FloatField(blank=True, null=True)),
                ('factura_corresponde_mes', models.DateField()),
                ('factura_creado', models.DateTimeField(auto_now_add=True)),
                ('factura_pagado_status', models.BooleanField(default=False, verbose_name='Status pago')),
                ('factura_contrato_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago_proveedor.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_pdf', models.FileField(upload_to='Facturas/pagos/')),
                ('pago_monto', models.FloatField(blank=True, null=True)),
                ('pago_metodo', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=40)),
                ('pago_creado', models.DateTimeField(auto_now_add=True)),
                ('pago_factura_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago_proveedor.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('proveedor_rfc', models.CharField(default='none', max_length=15, unique=True, verbose_name='RFC')),
                ('proveedor_email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pago_proveedor.Proveedor'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='complemento_pago_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago_proveedor.Pago'),
        ),
    ]
