# Generated by Django 2.1.5 on 2019-02-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complemento',
            old_name='complemento_pago_id',
            new_name='pago_id',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='pago_factura_id',
            new_name='factura_id',
        ),
    ]
