# Generated by Django 2.1.5 on 2019-02-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0002_auto_20190207_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complemento',
            old_name='pago_id',
            new_name='complemento_pago',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='factura_id',
            new_name='pago_factura',
        ),
    ]
