# Generated by Django 2.1.5 on 2019-02-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('pago_proveedor', '0003_auto_20190207_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contrato_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.Sucursal', verbose_name='Sucursal'),
        ),
    ]
