# Generated by Django 2.1.7 on 2019-03-19 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20190213_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pago_proveedor', '0004_contrato_contrato_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComplemento',
            fields=[
                ('complemento_id', models.IntegerField(blank=True, db_index=True)),
                ('complemento_pdf', models.TextField(max_length=100)),
                ('complemento_monto', models.FloatField(blank=True, null=True)),
                ('complemento_metodo', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=40)),
                ('complemento_creado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('complemento_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pago_proveedor.Pago')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical complemento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContrato',
            fields=[
                ('contrato_id', models.IntegerField(blank=True, db_index=True)),
                ('contrato_documento', models.TextField(max_length=100, verbose_name='Documento')),
                ('contrato_fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('contrato_fecha_termino', models.DateField(verbose_name='Termino')),
                ('contrato_dias_pago', models.CharField(max_length=100, verbose_name='Describa fechas de pago')),
                ('contrato_direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('contrato_monto', models.FloatField(verbose_name='Monto')),
                ('contrato_autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('contrato_status', models.BooleanField(default=True, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contrato_proveedor_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pago_proveedor.Proveedor')),
                ('contrato_sucursal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresa.Sucursal', verbose_name='Sucursal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contrato',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFactura',
            fields=[
                ('factura_id', models.IntegerField(blank=True, db_index=True)),
                ('factura_tipo', models.IntegerField(choices=[(1, 'Persona Fisica'), (2, 'Persona Moral')])),
                ('factura_xml', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('factura_pdf', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('factura_monto_total', models.FloatField(blank=True, null=True)),
                ('factura_iva_trasladado', models.FloatField(blank=True, null=True)),
                ('factura_iva_retenido', models.FloatField(blank=True, null=True)),
                ('factura_isr_retenido', models.FloatField(blank=True, null=True)),
                ('factura_corresponde_mes', models.DateField()),
                ('factura_creado', models.DateTimeField(blank=True, editable=False)),
                ('factura_pagado_status', models.BooleanField(default=False, verbose_name='Status pago')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('factura_contrato_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pago_proveedor.Contrato')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical factura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPago',
            fields=[
                ('pago_id', models.IntegerField(blank=True, db_index=True)),
                ('pago_pdf', models.TextField(max_length=100)),
                ('pago_monto', models.FloatField(blank=True, null=True)),
                ('pago_metodo', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=40)),
                ('pago_creado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pago_factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pago_proveedor.Factura')),
            ],
            options={
                'verbose_name': 'historical pago',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProveedor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('proveedor_rfc', models.CharField(db_index=True, default='none', max_length=15, verbose_name='RFC')),
                ('proveedor_email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proveedor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
