# Generated by Django 2.1.7 on 2019-10-11 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_trabajo',
            fields=[
                ('pt', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_lunes', models.BooleanField(default=False, verbose_name='Lunes')),
                ('pt_martes', models.BooleanField(default=False, verbose_name='Martes')),
                ('pt_miercoles', models.BooleanField(default=False, verbose_name='Miercoles')),
                ('pt_jueves', models.BooleanField(default=False, verbose_name='Jueves')),
                ('pt_viernes', models.BooleanField(default=False, verbose_name='Viernes')),
                ('pt_sabado', models.BooleanField(default=False, verbose_name='Sabado')),
                ('pt_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('pt_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cliente', verbose_name='Cliente')),
                ('pt_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario vendedor')),
            ],
            options={
                'verbose_name': 'Plan de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Registro_actividad',
            fields=[
                ('ra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('ra_hora_final', models.TimeField(auto_now_add=True, verbose_name='Hora Termino')),
                ('ra_monto_compra', models.FloatField(verbose_name='Monto de compra')),
                ('ra_observacion', models.CharField(max_length=300, verbose_name='Observación')),
                ('ra_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('ra_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cliente', verbose_name='Cliente')),
                ('ra_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario vendedor')),
            ],
            options={
                'verbose_name': 'Registro actividad vendedor',
                'verbose_name_plural': 'Registro actividad vendedores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registro_actividad',
            unique_together={('ra_cliente', 'ra_fecha_creacion')},
        ),
        migrations.AlterUniqueTogether(
            name='plan_trabajo',
            unique_together={('pt_cliente', 'pt_vendedor')},
        ),
    ]
