# Generated by Django 2.1.7 on 2019-10-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_actividad',
            options={'permissions': [('reg_activ_supervisor', 'Usuario con permiso de supervisor')], 'verbose_name': 'Registro actividad vendedor', 'verbose_name_plural': 'Registro actividad vendedores'},
        ),
    ]
