# Generated by Django 2.1.7 on 2019-10-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_trabajo', '0002_auto_20191011_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_trabajo',
            name='pt_cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='plan_trabajo',
            unique_together=set(),
        ),
    ]
