# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0009_departamento_limite_gasto'),
        ('pedidos', '0002_auto_20190117_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Rechazado')])),
                ('id_depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Departamento')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.Producto'),
        ),
    ]
