# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20190117_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='pedido_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Producto'),
        ),
    ]
