# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20190117_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'ordering': ['pedido_id'], 'verbose_name_plural': 'DETALLE DE PEDIDOS'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_depo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Departamento'),
        ),
    ]
