# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20190117_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Departamento'),
        ),
    ]
