# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresa', '0010_auto_20190118_1006'),
        ('pedidos', '0006_auto_20190117_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'ordering': ['detallepedido_pedido_id'], 'verbose_name_plural': 'DETALLE DE PEDIDOS'},
        ),
        migrations.RenameField(
            model_name='area',
            old_name='id_area',
            new_name='area_id_area',
        ),
        migrations.RenameField(
            model_name='detalle_pedido',
            old_name='pedido_id',
            new_name='detallepedido_pedido_id',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='id_marca',
            new_name='marca_id_marca',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='actualizado',
            new_name='pedido_actualizado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_pedido',
            new_name='pedido_fecha_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_pedido',
            new_name='pedido_id_pedido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='producto_codigo',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nombre_area',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_depo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='area',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='area',
            name='area_nombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre de area'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_cantidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='marca',
            name='marca_nombre',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre de Marca'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_id_depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_status',
            field=models.IntegerField(choices=[(1, 'Creado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%D', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
