# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20190118_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de area'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca_nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre de Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
