# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20190118_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_id_depo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresa.Departamento', verbose_name='Departamento'),
        ),
    ]
