# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20190118_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='detallepedido_total',
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_precio',
            field=models.FloatField(default='0'),
        ),
    ]
