# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0010_auto_20190119_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'ordering': ['detallepedido_pedido_id'], 'verbose_name_plural': 'Carrito compra'},
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='detallepedido_creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='detallepedido_pedido_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido', verbose_name='Numero de pedido'),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='detallepedido_precio',
            field=models.FloatField(default=0),
        ),
    ]
