# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_auto_20190119_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'ordering': ['detallepedido_pedido_id'], 'verbose_name_plural': 'Detalle de pedidos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.IntegerField(blank=True, choices=[(1, 'Uso Interno'), (2, 'Activo Fijo')], null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_productos/', verbose_name='Imagen'),
        ),
    ]
