# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_auto_20190122_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pertenece_sucursal',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
