# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 21:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factura_isr_retenido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_iva_retenido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_pdf',
            field=models.FileField(upload_to='Facturas/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_xml',
            field=models.FileField(upload_to='Facturas/xml/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
    ]
