# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0002_auto_20190125_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factura_iva_trasladado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_monto_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
