# Generated by Django 2.1.5 on 2019-01-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0003_auto_20190125_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contrato_autorizado',
            field=models.BooleanField(default=False, verbose_name='Autorizado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_documento',
            field=models.FileField(upload_to='Contratos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_fecha_inicio',
            field=models.DateField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_fecha_termino',
            field=models.DateField(verbose_name='Termino'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_monto',
            field=models.FloatField(verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago_factura_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago_proveedor.Factura'),
        ),
    ]
