# Generated by Django 2.1.5 on 2019-01-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0004_auto_20190128_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='factura_pagado_status',
            field=models.BooleanField(default=False, verbose_name='Status pago'),
        ),
    ]
