# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0005_factura_factura_pagado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='proveedor_rfc',
            field=models.CharField(default='none', max_length=15, verbose_name='RFC'),
        ),
    ]
