# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_proveedor', '0006_proveedor_proveedor_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_rfc',
            field=models.CharField(default='none', max_length=15, unique=True, verbose_name='RFC'),
        ),
    ]
